### ISSUE TITLE
Can you introduce the meaning for each column in longqc_sdust.txt ? 3KU

### ISSUE THREAD

**Issue by Velcon-Zheng** [yfukasawa/LongQC#1]
# Can you introduce the meaning for each column in longqc_sdust.txt ?

### For example with the pacbio sequel bam as input,

||column2|column3|column4|column5|column6|
|------|---|------|---|------|---|
|m64062_47008_47682     |  197   |674       |0.292   |-0.000    |0
m64062_0_35905            |   976  |   35905 |  0.027 |  -0.000  |  0
m64062_0_157               |     7      | 157     |  0.045 |  -0.000   |  0

### Thank you.

**Comment by yfukasawa** [comment]
Hi @Velcon-Zheng,

Thank you for your interest. I'll update README later.
Meanwhile, please see below.

Column1: read name
Column2: the number of bases masked
Column3: read length
Column4: fraction of masked bases, namely coulmn2/column3
Column5: average read QV (For Sequel CLR, ignorable)
Column6: the number of bases whose QV is higher than 7 (again ignorable for Sequel CLR)

Hope this helps.
