### ISSUE TITLE
Long time for processing

### ISSUE THREAD

**Issue by arunvv90** [yfukasawa/LongQC#10]
I am using 1.1.1 version from docker. I have used following command
python longQC.py sampleqc -x ont-ligation -p 6 -d -o /data/out_dir221 /data/Arun1.CCV.fastq
I have aborted the process because it did not finish even after 15 minutes.
My computer has 64 GB RAM and 6 CPU cores

Can you help me to optimize the performance?

**Comment by yfukasawa** [comment]
Hello @arunvv90,

Thanks for feedback, and sure, let us try to accelerate the performance.
How big your fastq file is, Arun1.CCV.fastq? sampleqc has mainly 2 steps: 1) collecting general stats like (length, QV, etc), and 2) computing coverage in your dataset. The bottlenecks in 2 steps are actually different.

Bottleneck for step 1 in my benchmark was actually I/O, storage performance seemed a main factor. If your file is big (e.g. >300 gigabytes), it can take ~ 1h.
If this is not the case, step 2 is more likely, you can try a rapid mode (but I should note that this will show less accurate results as a trade off).
Please just add **--fast** in your command.
`python longQC.py sampleqc -x ont-ligation -p 6 -d --fast -o /data/out_dir221 /data/Arun1.CCV.fastq`

Y.
