### ISSUE TITLE
 lq_coverage failing

### ISSUE THREAD

**Issue by choudharis2** [yfukasawa/LongQC#12]
Hi, 

I am using longQC for my sequel II data and it ran fine in the past but currently, it is giving me errors for some samples and other samples are running fine.
The surprising thing is that all the figures are generated but it fails to give the following error:

longQC::INFO:Generated coverage related plots.
lq_coverage : WARNING:Mode of lognormal has no value. Do estimation first.
Traceback (most recent call last):
  File "longQC.py", line 918, in <module>
    main(args)
  File "/longQC.py", line 63, in main
    args.handler(args)
  File "longQC.py", line 591, in command_sample
    or (lc.is_low_coverage() and float(lc.get_logn_mode()) < very_low_coverage_threshold) \
TypeError: float() argument must be a string or a number, not 'NoneType'

I have tried different very_low_coverage_threshold, went as low as 1.

I am using the following version:
 Project Name: longQC.py
 Start Date: 2017-10-10
 Version: 0.1

This is my command line 
`python longQC.py sampleqc -o Sample/longQC -x pb-sequel -s Sample Sample.ccs.fastq`

Please let me know where I am going wrong.

Thanks for your help!

**Comment by jforero2020** [comment]
I have the same error ........

**Comment by choudharis2** [comment]
Hi jforero2020,

Did you figure out the error?
 I am still getting the same error with different datasets also.

Thanks!

**Comment by jforero2020** [comment]
> Hi jforero2020,
> 
> Did you figure out the error?
> I am still getting the same error with different datasets also.
> 
> Thanks!

Not yet :(

**Comment by yfukasawa** [comment]
Hello @choudharis2 and @jforero2020,

Sorry for taking time to resolve this issue. It seemed to be a combination of different problems.
I've added some patches, and release v1.2.0.

You applied HiFi dataset coming from Sequel-II?
Error profile of HiFi (or CCS) is totally different from CLR, and minimap2 didn't work well with parameters for typical long read datasets. It could result in lower coverage than actual coverage.
Added a new option (**-x pb-hifi**) for this issue.

Also, the error happens when any read doesn't have coverage. This case was slipped off from testing, and added a new treatment for this.

Hope this resolves your issue.

Yoshinori

**Comment by shannonekj** [comment]
Hi @yfukasawa quick question & thanks for the `-x pb-hifi` update! I'm super excited to use it. I just want to make sure I'm feeding it the right data file. Should this raw sequencing file be the `*.fastq` one generates after the `*.subreads.bam` is processed through the software `ccs`?? 

So, correct usage would be:
`python longQC.py sampleqc -x pb-hifi -o out_dir input_reads.ccs.fastq`

Thank you! 
Shannon

**Comment by yfukasawa** [comment]
Hi @shannonekj,

Thank you for your interest in LongQC. sorry, not updated the README yet, but yes, it should generate stats for your CCS.
If the input is ccs reads, format doesn't matter (fastq, fasta, or uBam).

I should note that the parameters for pb-hifi was tuned for Q20 or better reads. Expected error rate is **1%** or lower (the latest default by PacBio dev team).
Some old CCS uses around 10% error (Q10), and still true for specific applications like Iso-seq, and in this case, `-x pb-sequel` would be better.

hope this helps.

Best,
Yoshinori

**Comment by shannonekj** [comment]
Perfect––this helps quite a bit. Thank you @yfukasawa!
