### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by gimnec** [yfukasawa/LongQC#17]
After the command: 
python longQC.py sampleqc -x pb-rs2 -o /data/out_dir /data/SRR10520596.fastq

The error: 
![Clip_27](https://user-images.githubusercontent.com/76786322/103747169-d5c65b00-5034-11eb-84cd-36deb1f9961c.png)

**Comment by yfukasawa** [comment]
Hi,

Is there `coverage_err.txt` and `coverage_out.txt` under `/data/out_dir/analysis/minimap2/`?
coverage_out.txt may be an empty file in this case.

One possible case is out of memory error happened, and your system (OS) might have killed the minimap2 process.
if this is the case, please try lower number of bases for minimap2 by `-I` option.

Like:
`python longQC.py sampleqc -I 400M -x pb-rs2 -o /data/out_dir /data/SRR10520596.fastq`

Y.

**Comment by gimnec** [comment]
@yfukasawa 

Yes, there are `coverage_err.txt` and `coverage_out.txt` files.
Also, `coverage_out.txt` is an empty file.

I tried the command with `--index` option but still got the same error.

**Comment by gimnec** [comment]
@yfukasawa 

I just tried `--index` again by lowering from 400M to 200M and it worked until the end!

Thank you again. Keep up all the good work!

**Comment by Malarky-PV** [comment]
Hi,
sorry to comment on a closed issue but I'm having a similar problem:
 File "/home/verba001/miniconda3/bin/longQC.py", line 956, in <module>
    main(args)
  File "/home/verba001/miniconda3/bin/longQC.py", line 62, in main
    args.handler(args)
  File "/home/verba001/miniconda3/bin/longQC.py", line 369, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

In my case I have no coverage_err.txt and coverage_out.txt files.

Do you have an idea what causing the problem?

**Comment by andreaschavez** [comment]
> Hi, sorry to comment on a closed issue but I'm having a similar problem: File "/home/verba001/miniconda3/bin/longQC.py", line 956, in main(args) File "/home/verba001/miniconda3/bin/longQC.py", line 62, in main args.handler(args) File "/home/verba001/miniconda3/bin/longQC.py", line 369, in command_sample df_mask = pd.read_table(lm.get_outfile_path(), sep='\t', header=None) File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper return func(*args, **kwargs) File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 683, in read_table return _read(filepath_or_buffer, kwds) File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read parser = TextFileReader(filepath_or_buffer, **kwds) File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in **init** self._engine = self._make_engine(self.engine) File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine return mapping[engine](self.f, **self.options) # type: ignore[call-arg] File "/home/verba001/miniconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in **init** self._reader = parsers.TextReader(self.handles.handle, **kwds) File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.**cinit** pandas.errors.EmptyDataError: No columns to parse from file
> 
> In my case I have no coverage_err.txt and coverage_out.txt files.
> 
> Do you have an idea what causing the problem?

I'm having the same error and I also don't have the coverage_err.txt and coverage_out.txt files. 

Does someone have a solution to this. Thanks.

**Comment by yfukasawa** [comment]
Hi @Malarky-PV and @andreaschavez,

Sorry, I didn't notice your queries.
Regarding your issue, compilation for some programs seems to have some issues when LongQC was installed at your ends. If programs ended with issues, you should see at least `coverage_err.txt`.

Could you please try below to confirm if it works?
`/path/to/LongQC/minimap2-coverage/minimap2-coverage`

If compilation worked well, you should see below message:

> Usage: minimap2-coverage [OPTION...] reference reads
Try `minimap2-coverage --help' or `minimap2-coverage --usage' for more
information.

Hope this helps.

Yoshinori
