### ISSUE TITLE
minimap2-coverage.c:565:9: error: implicit declaration of function 'compute_reliable_region' is invalid in C99

### ISSUE THREAD

**Issue by sanaek** [yfukasawa/LongQC#18]
Hi, I'm new to this, but im currently working with fast5 files generated by minion
trying to install longQC in my Mac, I get run ´LongQC/minimap2-coverage && make´ I get the following error

´minimap2-coverage.c:565:9: error: implicit declaration of function 'compute_reliable_region' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        compute_reliable_region(v, fopt.min_coverage, &regs, &mregs);
        ^
1 error generated.
make: *** [minimap2-coverage.o] Error 1´

can anyone help me on this?

Thank you

**Comment by yfukasawa** [comment]
hi @sanaek,

Which OS you currently use? I mean Mac OS version such as 10.xx.xx.
also, can I ask you to share output for below commands?

`clang -dumpversion`
`gcc -dumpversion`

Y.

**Comment by sanaek** [comment]
Hello @yfukasawa thank you for your answer

I recently updated to Mac 11.1 BigSur

the output of the commands is the following:

`clang -dumpversion
12.0.0
gcc -dumpversion
12.0.0`

Sanae

**Comment by yfukasawa** [comment]
Hi Sanae,

Thanks for sharing details - it helped. There seems to be some changs between clang11 and clang12, and the code hit this change.
I added a quick fix, and could you please download the latest codes from the repo and try again?
If there are still issues, kindly let me know. Thanks!

Y.

**Comment by sanaek** [comment]
Hi @yfukasawa 

Thank you for your help, that worked great!

I had issues latter with edlib installed via conda, but resolved installing via pip the version 1.3.8 (if anyone has this issue)

I'll close this now, thank you for your work!
