### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by m-gemmell** [yfukasawa/LongQC#19]
Hello

I hope all is well.

Sorry for the bother but I have an issue running longQC and was hoping for some help as I haven't been able to figure it out.

I believe I have everything installed correctly as per the instructions however when I run the below command to get sampleqc on a pacbio seuel bam file called 37.bam:

python /pub01/mgemmell/programs_chos_7/longqc/LongQC/longQC.py sampleqc -x pb-sequel -o 37_longqc_results 37.bam

I get the below:

longQC:2021-01-19 13:43:57,198:169:INFO:Cmd: /pub01/mgemmell/programs_chos_7/longqc/LongQC/longQC.py sampleqc -x pb-sequel -o 37_longqc_results 37.bam
longQC:2021-01-19 13:43:57,198:233:INFO:Preset "pb-sequel" was applied. Options --pb(--ont) is overwritten.
Traceback (most recent call last):
  File "/pub01/mgemmell/programs_chos_7/longqc/LongQC/longQC.py", line 956, in <module>
    main(args)
  File "/pub01/mgemmell/programs_chos_7/longqc/LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "/pub01/mgemmell/programs_chos_7/longqc/LongQC/longQC.py", line 235, in command_sample
    file_format_code = guess_format(args.input)
  File "/pub01/mgemmell/programs_chos_7/longqc/LongQC/lq_utils.py", line 125, in guess_format
    l = f.readline()
  File "/pub01/mgemmellprograms_chos_8/anaconda3/envs/longqc/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 4: invalid start byte

Any help would be appreciated and feel free to ask me any questions if it helps.

**Comment by davidoctaviobotero** [comment]
Same problem. Started today with the app. Any help will be appreciated.

**Comment by yfukasawa** [comment]
this may be caused by special character or specification change in PacBio bam file.
Just curious, your bam file is a file dumped by Sequel? or is there any intermediate step?
will check at my side.

In the meantime, if you convert your bam to fastq/fasta format, problem might disappear.

Yoshinori

**Comment by davidoctaviobotero** [comment]
Hi Yoshinori,

Yes, the bam file was dumped by sequel "subread.bam". As I know this the file is ready for downstream analyses. I will try samtools conversion to fasta. Thank you, I will let you know the final result.

**Comment by m-gemmell** [comment]
Hello

I got the bam files from: https://github.com/PacificBiosciences/DevNet/wiki/Microbial-Multiplexing-Data-Set---48-plex:-PacBio-Sequel-II-System,-Chemistry-v2.0,-SMRT-Link-v8.0-Analysis

I changed the file names to make them shorter. 

Converting the bam files to fastq worked perfectly.

Thanks for you help!

**Comment by yfukasawa** [comment]
Thanks both, that sounds some encoding changes happen on PacBio bam file. I will check with PacBio people when I have a chance.
The problematic code just checks if a given bam is gzipped or not, but maybe pacbio bam is not being encoded in standard UTF-8 anymore.
will check the provided file, much appreciated!

Y.

**Comment by yfukasawa** [comment]
PacBio seems to have started using compressed BAMs rather than uncompressed BAMs as a default. This hit a bug in the code - l_text (uint32_t) was loaded as a string of UTF-8 (my misunderstanding); hence decoding error.
Now only 4 bytes are read from and checked.

Y.
