### ISSUE TITLE
struct.error: 'i' format requires

### ISSUE THREAD

**Issue by davidoctaviobotero** [yfukasawa/LongQC#20]
Hi Yoshinori,

Thank you for this tool.

After processing some reads I get an error of format. Previously you solved a problem related to UTF-8 format. You guessed it was related to the new PacBio sequel codification format. Finally, I could start to run the algorithm of longQC.py "sampleqc" and get the following error, I do not if it is related to the same problem. Any help will be appreciated. Thank you,

`python /opt/LongQC/longQC.py sampleqc -x pb-sequel -o ./PacBio_QC/ chk_PacBio_/m54336U_201216_191137.subreads.bam -p 15 -m 2 -i 128
longQC:2021-01-25 16:29:47,375:169:INFO:Cmd: /opt/LongQC/longQC.py sampleqc -x pb-sequel -o ./PacBio_QC/ chk_PacBio_/m54336U_201216_191137.subreads.bam -p 15 -m 2 -i 128
longQC:2021-01-25 16:29:47,376:233:INFO:Preset "pb-sequel" was applied. Options --pb(--ont) is overwritten.
lq_utils:2021-01-25 16:29:47,383:127:DEBUG:chk_PacBio_/m54336U_201216_191137.subreads.bam is a compressed BAM.
longQC:2021-01-25 16:29:47,383:238:INFO:Temporary work file was made at ./PacBio_QC/analysis/pbbam_converted_seq_file.fastq
longQC:2021-01-25 16:31:03,240:306:INFO:Computation of the low complexity region started for a chunk 0
lq_mask:2021-01-25 16:31:17,932:111:INFO:New job was submitted: in->./PacBio_QC/analysis/tmp_0.fastq, out->./PacBio_QC/analysis/tmp_0.txt
longQC:2021-01-25 16:31:17,933:311:INFO:Adapter search is starting for a chunk 0.
longQC:2021-01-25 16:31:17,933:327:INFO:Computation of the GC fraction started for a chunk 0
lq_adapt:2021-01-25 16:32:09,463:77:INFO:2330 reads were skipped due to their short lengths.
lq_adapt:2021-01-25 16:32:09,519:90:INFO:Adapter Sequence: ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT, max identity:0.977778 and the number of trimmed reads: 67
lq_utils:2021-01-25 16:32:17,424:380:INFO:list for subsample is not initialized. Initializing now.
lq_adapt:2021-01-25 16:32:19,634:42:INFO:2333 reads were skipped due to their short lengths.
lq_adapt:2021-01-25 16:32:19,635:92:INFO:Adapter Sequence: ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT, max identity:0.956522 and the number of trimmed reads: 64
longQC:2021-01-25 16:33:17,551:332:INFO:Adapter search has done for a chunk 0.
longQC:2021-01-25 16:33:17,551:342:INFO:subsample finished for chunk 0.
longQC:2021-01-25 16:34:31,081:306:INFO:Computation of the low complexity region started for a chunk 1
lq_mask:2021-01-25 16:34:46,149:111:INFO:New job was submitted: in->./PacBio_QC/analysis/tmp_1.fastq, out->./PacBio_QC/analysis/tmp_1.txt
longQC:2021-01-25 16:34:46,149:311:INFO:Adapter search is starting for a chunk 1.
longQC:2021-01-25 16:34:46,150:327:INFO:Computation of the GC fraction started for a chunk 1
lq_adapt:2021-01-25 16:35:46,389:77:INFO:1358 reads were skipped due to their short lengths.
lq_adapt:2021-01-25 16:35:46,389:90:INFO:Adapter Sequence: ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT, max identity:0.957447 and the number of trimmed reads: 63
lq_adapt:2021-01-25 16:35:55,091:42:INFO:1363 reads were skipped due to their short lengths.
lq_adapt:2021-01-25 16:35:55,091:92:INFO:Adapter Sequence: ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT, max identity:0.957447 and the number of trimmed reads: 62
longQC:2021-01-25 16:36:40,406:332:INFO:Adapter search has done for a chunk 1.
Traceback (most recent call last):
  File "/opt/LongQC/longQC.py", line 956, in <module>
    main(args)
  File "/opt/LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "/opt/LongQC/longQC.py", line 341, in command_sample
    s_reads = pool_res['subsample'].get()
  File "/home/mldbotero/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/mldbotero/anaconda3/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/mldbotero/anaconda3/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/mldbotero/anaconda3/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)`

**Comment by yfukasawa** [comment]
Hi David,

Sorry for getting back to this late, but thanks for raising an issue.
will get into this.

Yoshinori

**Comment by yfukasawa** [comment]
Hello David,

Sorry for getting back late... it has taken time to understand the issue.
If you specify lower number in `-m` option than 2, the error would disappear.

e.g.
`python /path/to/longQC.py sampleqc -x pb-sequel - o input -m 1`

The module used by LongQC uses a built-in multiprocessing module, and one of functions (_send_bytes()) can't deal with a large data. (Python internally uses the pickle for this type of communication, and it looks there is a limit for pickle size in this context).

Sorry for inconvenience, but hope this helps.

Best,
Y.

**Comment by davidoctaviobotero** [comment]
Hi Yoshi,

Many tahnks. We are going to test it,

Best,


David Octavio Botero Rozo, PhD

Cellular: +57 315 6490601
