### ISSUE TITLE
How did the author find the adapter sequences for Pacbio sequel?

### ISSUE THREAD

**Issue by tangmaomao16** [yfukasawa/LongQC#21]
I read the longQC.py script, there are some adapter sequences. For example,
```
    if args.preset:
        p = args.preset
        if p == 'pb-rs2':
            args.pb = True
            args.adp5 = "ATCTCTCTCTTTTCCTCCTCCTCCGTTGTTGTTGTTGAGAGAGAT" if not args.adp5 else args.adp5
            args.adp3 = "ATCTCTCTCTTTTCCTCCTCCTCCGTTGTTGTTGTTGAGAGAGAT" if not args.adp3 else args.adp3
            minimap2_params    = "-Y -l 0 -q 160"
            minimap2_med_score_threshold = 80
            if args.short:
                minimap2_med_score_threshold_short = 60
        elif p == 'pb-sequel':
            args.pb = True
            args.sequel = True
            args.adp5 = "ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT" if not args.adp5 else args.adp5
            args.adp3 = "ATCTCTCTCAACAACAACAACGGAGGAGGAGGAAAAGAGAGAGAT" if not args.adp3 else args.adp3
            minimap2_params = "-Y -l 0 -q 160"
            minimap2_med_score_threshold = 80
            if args.short:
                minimap2_med_score_threshold_short = 60

```
For example, I have done a 'pb-sequel' sequencing, and I don't know what the adapter sequence is. Are the adapter sequences in the longQC.py script correct for my case?  How can I judge it?
How did the author find the adapter sequences for Pacbio sequel? Could you show us the reference website?

**Comment by yfukasawa** [comment]
Hi @tangmaomao16,

Sorry for late reply.

PacBio Sequel system trims off adapter on the instrument computer, so you basically don't have to worry.
But in some rare cases, adapter trimming was not done well (e.g. challenging datasets in our paper), so we decided to keep this code.

For RS-II, you'll find information on [this guide](https://www.pacb.com/wp-content/uploads/2015/09/Guide-Pacific-Biosciences-Template-Preparation-and-Sequencing.pdf), for example.

Sequel platform outputs adapter sequencing in fasta format along subread file.
I've seen only the sequence in the code so far, but if you need to apply another sequence, you can specify through `--adapter_5` and/or `--adapter_3` options.

Just FYI, removed adapter sequences should be stored in scraps.bam file, if the specification remains the same.

Hope this helps.

Best,
Yoshinori
