### ISSUE TITLE
too high non-sense read fraction

### ISSUE THREAD

**Issue by grpiccoli** [yfukasawa/LongQC#27]
When i run:
python longQC.py sampleqc -x pb-hifi -o longqc ccs.bam
I get a message saying too high non-sense read fraction 
Non-sense fraction is 0.647
but if I use:
python longQC.py sampleqc -x pb-sequel -o longqc ccs.bam
Non-sense fraction goes down to 0.282

I a trying to analyse a Sequel II Hifi run, which result would be the correct one?

It looks like the only thing that changes for minimap2-coverage are the database kmer size parameter?
HiFi : -k 15
Sequel : -k 12

**Comment by yfukasawa** [comment]
Hi @grpiccoli,

Thank you for your interest in LongQC.
If your data is HiFi, I mean expected error rate is Q20 or better, the first option is the one. -k 12 is too short for HiFi from our statistics. I'm wondering the coverage might be still insufficient for your target genome/transcriptiome/etc. How coverage plots looks like?

Yoshinori

**Comment by grpiccoli** [comment]
FastQC tells me I got between Q35 and Q80 but the average is >Q40
Here are the coverage plots using pb-hifi
![image](https://user-images.githubusercontent.com/29615664/116806372-b1146700-ab80-11eb-940f-495f74ffbc20.png)

And here using pb-sequel
![image](https://user-images.githubusercontent.com/29615664/116806396-d86b3400-ab80-11eb-8254-9035d590c150.png)

And here is the k-mer coverage analysis I got from genomeScope
![image](https://user-images.githubusercontent.com/29615664/116806414-f8025c80-ab80-11eb-8f15-d04b462786be.png)

**Comment by yfukasawa** [comment]
Let me close this issue. When you encounter problem in this context, feel free to reopen.
Thank you.

Y.
