### ISSUE TITLE
How to run LongQC with Singularity

### ISSUE THREAD

**Issue by zhxiaokang** [yfukasawa/LongQC#31]
Hi, I have no problem running LongQC with Docker with the command in the Doc:
```
docker run -it \
-v YOUR_INPUT_DIR:/input \
-v YOUR_OUTPUT_DIR:/output \
longqc sampleqc \
-x pb-sequel \ **specify a preset and change accordingly.**
-p $(nproc) \ **number of process/cores, this uses all of your cores. change accordingly.**
-o /output/YOUR_SAMPLE_NAME \ **keep /output as this is binded.**
/input/YOUR_INPUT_READ_FILE **keep /input as this is binded.**
```
But because of Docker's high privilege requirement, it is not allowed on our server. But Singularity is supported on the server. So I converted LongQC's Docker image into a Singularity file `longqc.sif`, but I'm having problems getting it run with singularity. Do you have any suggestions on how to run this `longqc.sif` with Singularity? Thank you in advance!

**Comment by yfukasawa** [comment]
Hi @zhxiaokang,

Thank you for having interest in LongQC and your comment!
Indeed, Singularity seems to be quite popular among computer clusters, but I haven't covered Singularity yet. Can I ask what type of issue happened when you run on Singularity?

Y.

**Comment by zhxiaokang** [comment]
Hi @yfukasawa ,

Thank you for the quick reply. When I tried `singularity run longqc.sif`, I got the error `FATAL: "longQC.py": executable file not found in $PATH`. On the other hand, if I run a similar command `docker run longqc`, I got the nice expected HELP doc.

**Comment by yfukasawa** [comment]
Hi @zhxiaokang,

Thank you for your reply, and ok I understood your issue.
Some modification on the line 51 in Dockerfile would fix on Singularity, like `ENV PATH="$HOME/LongQC:$PATH" `

https://github.com/yfukasawa/LongQC/blob/113f60c19c1a2738e1be14b072c3885db7eb91f2/Dockerfile#L51

I did a lazy coding (/root was hard coded), and this seems to have caused the issue at your end.
$HOME equals /root in a typical Docker environment, but I learned $HOME can be inherited from the host on Singularity.
Kindly let me know if this doesn't work.

Y.

**Comment by zhxiaokang** [comment]
Hi, I tried modifying line 51 (the Dockerfile is in the directory `$HOME/LongQC`, which is the folder of the whole GitHub repository). And then did the following:
```
docker build -t longqc:latest .  # in the directory of $HOME/LongQC 
singularity build longqc.sif docker-daemon://longqc:latest
```
Then I have longqc.sif built from the Docker image. Then:
```
singularity run longqc.sif
```
Then the same error: `FATAL: "longQC.py": executable file not found in $PATH`

**Comment by yfukasawa** [comment]
sorry for delay. I've checked how Singularity works and some practices.
In Singularity, I learned that the above is not good practice as $HOME can be different.

this is just FYI, PATH for LongQC seems not to work in your Singularity image.
You can try something like:
`singularity shell longqc.sif`
then, inside of the shell:
`Singularity>ls $HOME/LongQC`
`Singularity>echo $PATH`

Also, another person kindly shared his Dockerfile before. it would be helpful for your situation.
https://github.com/yfukasawa/LongQC/issues/22

Y.

**Comment by zhxiaokang** [comment]
Hi, thank you for the hints. `echo $PATH` gives me: `/LongQC:/opt/conda...`. I guess that's why it complains executable file 'longQC.py' not found in $PATH, since the `/LongQC` doesn't exist. I tried to change `$HOME` in the Dockerfile to a hard directory, but that won't help.

I also tried the Dockerfile provided at #22 and it almost worked: the converted singularity image can be run with `longqc.sif --help`, but then I don't know how to set the parameters (Docker requires to mount the dir but Singularity is something different though) for command 'longqc.sif sampleqc'

**Comment by yfukasawa** [comment]
Thanks for following up. $HOME isn't expanded or becomes empty with ENV command in Docker (still investigating), and maybe this happened at your environment either.

In any case, I'm glad to hear it works on your end.
Re. binding of dir(s) between your host OS and Singularity container, I have no expertise on it unfortunately.
As long as LongQC executables in the container can read and write in a dir, it should work.

[https://singularity-tutorial.github.io/05-bind-mounts/](https://singularity-tutorial.github.io/05-bind-mounts/)

This page says your host's home dir is automatically mounted onto Singularity's container, so somewhere under your home may work without binding.

Y.

**Comment by yfukasawa** [comment]
let me close this thread, and feel free to reopen when needed.
Y.
