### ISSUE TITLE
Sequencing kit for -x

### ISSUE THREAD

**Issue by zhxiaokang** [yfukasawa/LongQC#32]
Hi, as stated on the GitHub page, for ONT data, there are two optional kits to choose from: 1D ligation and rapid sequencing kit. But as I understand from the ONT document here: [https://nanoporetech.com/sites/default/files/s3/Product_brochure_Final_July_2018.pdf](https://nanoporetech.com/sites/default/files/s3/Product_brochure_Final_July_2018.pdf) (pages 4 to 7 about available kits for library preparation), both are kits for DNA library preparation. But how about RNA? We actually used cDNA-PCR Sequencing Kit in our project, which is a type of RNA library.

**Comment by yfukasawa** [comment]
Hi @zhxiaokang, thanks for asking.

You can apply either ligation kit or rapid kit configuration.
On the top of this, for RNA-based application, option `--transcript (or -t)` might be of help as homogeneous coverage cannot be expected.

Also, other than this point, adapter sequences would be different between different ONT kits.
Do you know adapter sequences for your cDNA kit?
If you give sequences for `--adapter_5'` and `--adapter_3'` options, you can overwrite default adapter seqs by these options.

I'll add adapter sequences and some as a new config if you provide materials/sequences.
Thanks, and hope this helps.

Y.

**Comment by zhxiaokang** [comment]
Hi, thank you for the detailed explanation!

Just to make sure: by specifying the `--adapter_5'` and `--adapter_3'` options, the `-x` option will be overwritten and ignored, is that correct?

These are the adapter sequences we used in our kit (PCR-cDNA Barcoding Kit (SQK-PCB109)):

```
Adapter Y top:
5'- GGCGTCTGCTTGGGTGTTTAACCTTTTTTTTTTAATGTACTTCGTTCAGTTACGTATTGCT -3'

Adapter Y bottom:
5'- GCAATACGTAACTGAACGAAGT -3'
```

**Comment by yfukasawa** [comment]
Thanks for sharing sequence! I'll try to check at my side.

>the -x option will be overwritten and ignored, is that correct?

technically speaking, -x options specifies multiple parameters, and adapter sequence is just one of them.
--adapter_x' option will overwrites just adapter seq in -x config, so please use `-x ont-xxx` for the other ONT parameters.

Thanks.
