### ISSUE TITLE
AttributeError: 'Rectangle' object has no property 'normed'

### ISSUE THREAD

**Issue by tarah28** [yfukasawa/LongQC#4]
Hello. I just tried your program and after increasing number for (-p) was able to get further but now have new error. My input file is demultiplexed with qcat, concatenated into one fastq. Any ideas? Looking forward to using this software!

 `python ~/programs/LongQC/longQC.py sampleqc -x ont-ligation -o ontqc -p 4 Cf_KPC_all.fastq`
longQC:2020-06-04 13:38:43,599:166:INFO:Cmd: /home/tarah/programs/LongQC/longQC.py sampleqc -x ont-ligation -o ontqc -p 4 Cf_KPC_all.fastq
longQC:2020-06-04 13:38:43,599:216:INFO:Preset "ont-ligation" was applied. Options --pb(--ont) is overwritten.
longQC:2020-06-04 13:38:43,733:288:INFO:Computation of the low complexity region started for a chunk 0
lq_mask:2020-06-04 13:38:43,784:111:INFO:New job was submitted: in->ontqc/analysis/tmp_0.fastq, out->ontqc/analysis/tmp_0.txt
longQC:2020-06-04 13:38:43,785:293:INFO:Adapter search is starting for a chunk 0.
longQC:2020-06-04 13:38:43,785:309:INFO:Computation of the GC fraction started for a chunk 0
lq_utils:2020-06-04 13:38:44,020:358:INFO:list for subsample is not initialized. Initializing now.
lq_adapt:2020-06-04 13:38:44,086:76:INFO:694 reads were skipped due to their short lengths.
lq_adapt:2020-06-04 13:38:44,086:89:INFO:Adapter Sequence: AATGTACTTCGTTCAGTTACGTATTGCT, max identity:0.758621 and the number of trimmed reads: 1
lq_adapt:2020-06-04 13:38:44,218:41:INFO:694 reads were skipped due to their short lengths.
lq_adapt:2020-06-04 13:38:44,218:91:INFO:Adapter Sequence: GCAATACGTAACTGAACG, max identity:0.842105 and the number of trimmed reads: 20
longQC:2020-06-04 13:38:44,563:314:INFO:Adapter search has done for a chunk 0.
longQC:2020-06-04 13:38:44,563:324:INFO:subsample finished for chunk 0.
longQC:2020-06-04 13:38:44,563:344:INFO:Input file parsing was finished. #seqs:3591, #bases: 11155437
lq_mask:2020-06-04 13:38:44,563:114:INFO:Waiting completion of all of jobs...
lq_mask:2020-06-04 13:38:44,658:117:INFO:sdust jobs finished.
lq_mask:2020-06-04 13:38:44,661:87:INFO:sdust output file ontqc/longqc_sdust.txt was made.
lq_mask:2020-06-04 13:38:44,669:93:INFO:tmp file ontqc/analysis/tmp_0.fastq was removed.
lq_mask:2020-06-04 13:38:44,669:93:INFO:tmp file ontqc/analysis/tmp_0.txt was removed.
longQC:2020-06-04 13:38:44,669:348:INFO:Summary table ontqc/longqc_sdust.txt was made.
longQC:2020-06-04 13:38:44,695:354:DEBUG:Highly masked seq list:

longQC:2020-06-04 13:38:44,739:393:INFO:Subsampled seqs were written to a file. #seqs:3591
lq_exec:2020-06-04 13:38:44,749:26:INFO:below command is executed: -Y -l 0 -q 160 -k 15 -w 5 -I 4G -p 160 -t 4 Cf_KPC_all.fastq ontqc/analysis/subsample.fastq
lq_exec:2020-06-04 13:38:44,749:27:INFO:/home/tarah/programs/LongQC/minimap2_mod/minimap2-coverage is started.
longQC:2020-06-04 13:38:44,750:421:INFO:Overlap computation started. Process is 14834
lq_gcfrac:2020-06-04 13:38:44,750:52:INFO:Mean GC composition: 0.510
Traceback (most recent call last):
  File "/home/tarah/programs/LongQC/longQC.py", line 917, in <module>
    main(args)
  File "/home/tarah/programs/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/home/tarah/programs/LongQC/longQC.py", line 424, in command_sample
    gc_read_mean, gc_read_sd = lg.plot_unmasked_gc_frac(fp=fig_path_gc)
  File "/home/tarah/programs/LongQC/lq_gcfrac.py", line 54, in plot_unmasked_gc_frac
    plt.hist(self.r_frac, alpha=0.3, bins=np.arange(min(self.r_frac), max(self.r_frac) + b_width, b_width), color='blue', normed=True)
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2610, in hist
    if data is not None else {}), **kwargs)
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6808, in hist
    p.update(kwargs)
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/tarah/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 1002, in _update_property
    .format(type(self).__name__, k))
AttributeError: 'Rectangle' object has no property 'normed'

**Comment by yfukasawa** [comment]
Hello @tarah28,

Sorry for inconvenience, but thank you for reporting this!

Demultiplexed by qcat should be no problem with LongQC (guppy-barcoder is also fine as I tested this one).
Concatenating is a bit annoying for ONT, and I'm working to accept multiple fastq files. In the meantime, thank you, that's perfect.

I've pushed some new codes for a (possible) matplotlib issue. Hopefully, this will resolve your case.
Could you please download new codes and try again?

If you're ok, could you please share the version of your matplotlib?
To get the version, please type in your python:
`>>> import matplotlib`
`>>> matplotlib.__version__`
`'2.1.2'`

**Comment by tarah28** [comment]
Hello @yfukasawa! Thank you for replying. My matplotlib version is 3.2.1. I re-ran the command (must have -p > 1 or does not run). 
`python ~/programs/LongQC/longQC.py sampleqc -x ont-ligation -p 4 -o ontqc Cf_KPC_all.fastq`
Seemed to run ok!
What are the headers for the textfile output please? I think I can figure out but wanted to check
`head longqc_sdust.txt`
cd9eaec6-33ec-4d92-bbb8-2d3d8dcb9aef    0       1342    0.000   10.065  1102
f191d5eb-dbd7-4945-a635-797c6ac0bb43    0       222     0.000   10.135  182
e73b614e-ad2c-4190-8208-a5985c6ed063    0       219     0.000   9.066   165
9a544f3e-51eb-4206-b8ba-bf727ad92373    0       729     0.000   10.067  607
f1db8c1a-494b-4ca1-84a4-66965a6204a2    88      876     0.100   12.026  794

Also produced 4 figures successfully (avg_qv, gcfrac, length, masked_region)

Thanks so much for your help!

**Comment by yfukasawa** [comment]
Hi @tarah28,

thank you for sharing matplotlib version! I'll check the ver 3 or higher. It may take a few hours to run if the file size is big, and in such a case, please increase -p number (if your machine has more CPU cores).

Regarding the columns, sorry for inconvenience. I'll update the README. Please see below.

Column1: read name
Column2: the number of bases masked (MDUST algorithm)
Column3: read length
Column4: fraction of masked bases, namely coulmn2/column3
Column5: average read QV (For Sequel CLR, ignorable)
Column6: the number of bases whose QV is higher than 7 (again ignorable for Sequel CLR)

I hope this helps.

**Comment by tarah28** [comment]
Yes, thanks again! Good job on the program for quick QC of long reads!
