### ISSUE TITLE
longQC.py error

### ISSUE THREAD

**Issue by sekhwal** [yfukasawa/LongQC#43]
Hi, I am trying to run longQC.py with the following command. However, it is showing following error. Please suggest.

python longQC.py sampleqc -x pb-rs2 -o /longqc/ merge.fastq.gz

error:

Traceback (most recent call last):
  File "/media/bmaurice/Data2/Hybrid_assembly_virus/DMV10_IBV/longqc/LongQC/longQC.py", line 20, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by Sanrrone** [comment]
Hi @sekhwal ,
Is a common error when you don't have `pandas`. try to run `pip3 install pandas`

**Comment by yfukasawa** [comment]
many thanks for @Sanrrone!
Let me close this issue for now, and kindly open when further input needed.
