### ISSUE TITLE
Flanking region analysis plot

### ISSUE THREAD

**Issue by maguileraf** [yfukasawa/LongQC#45]
In the Flanking region analysis plot, what does the y-axis represent and how is it calculated?

**Comment by yfukasawa** [comment]
Hi @maguileraf ,

Sorry for delay, but thank you for contacting.
y-axis shows the number of reads: basically artificial flanking sequences (e.g. adapter) are not aligned well when we map all-vs-all using minimap, and LongQC seeks zero or extremely low coverage region in both terminals. if there is no such a sequence in one end, expectation would be there is a certain coverage from very end and you would see high peak at 0 in x-axis.

Some explanation is available in our supplementary information:  https://doi.org/10.25387/g3.11516004.

I hope this answer helps your question, and let me close this ticket for now.

Y.
