### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by RenzoTale88** [yfukasawa/LongQC#5]
Good afternoon,
I'm trying to run LongQC on a pacbio sequel library in fastq format.
The software starts just fine, but then crashes with the following error:
```
longQC:2020-06-08 15:02:23,100:573:INFO:Generating coverage related plots...
lq_coverage:2020-06-08 15:02:23,199:120:INFO:Estimating coverage distribution..
Traceback (most recent call last):
  File "/PATH/TO/Andrea/LongQC/longQC.py", line 920, in <module>
    main(args)
  File "/PATH/TO/Andrea/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/PATH/TO/Andrea/LongQC/longQC.py", line 577, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/PATH/TO/Andrea/LongQC/lq_coverage.py", line 121, in __init__
    self.__est_coverage()
  File "/PATH/TO/Andrea/LongQC/lq_coverage.py", line 220, in __est_coverage
    model_main_comp = self.__est_coverage_dist_gmm(k_i=2)
  File "/PATH/TO/Andrea/LongQC/lq_coverage.py", line 545, in __est_coverage_dist_gmm
    nonzeros  = self.df[LqCoverage.COVERAGE_COLUMN].values[np.nonzero(self.df[LqCoverage.COVERAGE_COLUMN])]
  File "<__array_function__ internals>", line 6, in nonzero
  File "/PATH/TO/Andrea/myanaconda/longqc/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1896, in nonzero
    return _wrapfunc(a, 'nonzero')
  File "/PATH/TO/Andrea/myanaconda/longqc/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/PATH/TO/Andrea/myanaconda/longqc/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapit
    result = wrap(result)
  File "/PATH/TO/Andrea/myanaconda/longqc/lib/python3.7/site-packages/pandas/core/generic.py", line 1918, in __array_wrap__
    return self._constructor(result, **d).__finalize__(self)
  File "/PATH/TO/Andrea/myanaconda/longqc/lib/python3.7/site-packages/pandas/core/series.py", line 292, in __init__
    f"Length of passed values is {len(data)}, "
ValueError: Length of passed values is 1, index implies 5000.
```
Not sure if the problem is with the data or with the dependencies. 
Thanks for the help
Andrea

**Comment by yfukasawa** [comment]
Hello @RenzoTale88,

thank you for your interest to our tool!
Could you please share the log for minimap2 (coverage_err.txt). It is located under your output (specified by -o option). In the directory, /analysis/minimap2/coverage_err.txt should exist.
Also, may I ask whether the number of lines for /analysis/minimap2/coverage_out.txt is 5000 (default)? I expect some error might have happened for this step, but please let me ask the above questions.

Thanks.

**Comment by RenzoTale88** [comment]
Hi @yfukasawa and thanks for the very quick reply!
This is the output in coverage_err.txt:
```
Homopolymer compression is not applied.
Warning: Apply default c=3 instead.
Warning: -s shouldn't be zero. Apply default s=100000 instead.
Warning: Apply default g=10000 instead.
Warning: Apply default n=3 instead.
Warning: Apply default m=40 instead.
Warning: Apply default s=25 instead.
Warning: Apply default a=2000 instead.
Warning: Apply default r=0.4 instead.
=== Parameters are listed below ===
Inputs are target: m54071_171021_203330.subreads.fastq, query: /PATH/TO/Andrea/SOFTWARE/LongQC/analysis/subsample.fastq
kmer 12, window 5, index loading size 4000000000
min-score 40, min-score-med 80, min-score-good 160, max-gap 10000, min-cnt 3
Homo-polymer compression: 0, Filtering: 0
max-overhang 2000, min-overlaplen 0, min-overapratio 0.40
num of threads 3, num of query seqs 100000
===
[M::main::154.127*2.28] loaded/built the index for 607906 target sequence(s)
[M::worker_pipeline::949.149*2.88] mapped 5000 sequences. (Peak RSS: 27.463 GB)
[M::main::1009.607*2.85] loaded/built the index for 218449 target sequence(s)
[M::worker_pipeline::1529.924*2.90] mapped 5000 sequences. (Peak RSS: 27.463 GB)

[M::main] Real time: 1530.462 sec; CPU: 4438.787 sec
```
Not sure, I didn't change any of the default parameters. The command line was just:
``` python longQC.py sampleqc --ncpu 4 -x pb-sequel -o $PWD/LongQC lib1.subreads.fastq```

Thanks for the help
Andrea

**Comment by yfukasawa** [comment]
Hi @RenzoTale88,

Thank you for sharing the log file! It did help to pinpoint the cause of the issue.
The step looks to have finished successfully, and another possibility is maybe library dependent issue.

Could you please share the version of python Pandas in your environment?
You can get the version by typing below in python.
`>>> import pandas`
`>>> pandas.__version__`

I think it would be 0.24.0 or higher.
In the meantime, I'll check in my env and try to push new codes to deal with that if this is the case.

**Comment by RenzoTale88** [comment]
Hi, just checked and my pandas version is 1.0.4. Perhaps some very recent release can have changed some of the syntax of the functions. Can you specify a version that you're sure is working with the software?

**Comment by yfukasawa** [comment]
Thanks.
Sure, I've developed using an old version, 0.22.0.
If you can downgrade to this version, that issue would be resolved.
