### ISSUE TITLE
Error running  the docker image

### ISSUE THREAD

**Issue by PavithraV0223** [yfukasawa/LongQC#58]
Greetings, 
I'm trying to build the docker image but it is taking longer time to build the image of the LongQC and it automatically shuts down like nothing was run. Even if I manage to run it, I see an empty longqc text file in the minimapcoverage folder. I'm not sure if this is the way it should work. But, once I try running docker with the built image. It says the longqc:latest is not found. I suppose the longqc is not building properly. Additionally, it also gives me an the below error. 

Error response from daemon: pull access denied for longqc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by yfukasawa** [comment]
Hi @PavithraV0223,

Thanks for your interests in our app.
Looks like your building failed due to some reason. Did you download the Dockerfile and then build the image against it?

`wget https://raw.githubusercontent.com/yfukasawa/LongQC/master/Dockerfile`

Yoshinori

**Comment by yfukasawa** [comment]
Self-follow-ups. Docker limits computational resources, and it kills the process internally if the resource such as RAM is not sufficient. If this is the case, simple workaround is increasing the resources (e.g., more RAMs, CPU cores, etc.)

**Comment by yfukasawa** [comment]
After monitoring, it seems that the issue has been resolved.
As a result, I will proceed to close it.
