### ISSUE TITLE
Issue with -v /input /output

### ISSUE THREAD

**Issue by kiranpatil222** [yfukasawa/LongQC#59]
Hi,

I am new docker, I have build the LongQC docker image, and ran with below command
`docker run 
-v /data/shared/clinical/LongRead/Data:/input 
-v /data/shared/clinical/LongRead/Data:/output 
longqc sampleqc 
-x pb-sequel 
-p 60 
-o /data/shared/clinical/LongRead/Data/175841_s1 
bampath.txt`

Input i tried with `input file /input/data/shared/clinical/LongRead/Data/m84011_220902_175841_s1.hifi_reads.bam does not exist` and gave abs path in txt file for both instance it says file doest exists 

Is there something wrong with my mount -v ? how should one give the input BAM

**Comment by yfukasawa** [comment]
Hi @kiranpatil222,

Thanks for your interest in our app.
kindly read the below instruction for docker if you haven't.

>docker run -it \
>-v YOUR_INPUT_DIR:/input \
>-v YOUR_OUTPUT_DIR:/output \
>longqc sampleqc \
>-x pb-sequel \ **specify a preset and change accordingly.**
>-p $(nproc) \ **number of process/cores, this uses all of your cores. change accordingly.**
>-o /output/YOUR_SAMPLE_NAME \ **keep /output as this is binded.**
>/input/YOUR_INPUT_READ_FILE **keep /input as this is binded.**

The path `/data/shared/clinical/LongRead/Data` should exist in your host OS, which doesn't exist in your docker container. this is why binding is important like `/data/shared/clinical/LongRead/Data` -> `/output`.
In this case, -o option should be simply like `-o /output/175841_s1` as mentioned above. The same goes for the input, if your bam file exists under `/data/shared/clinical/LongRead/Data/` in your host OS, then the input path should be `/input/m84011_220902_175841_s1.hifi_reads.bam`.

BTW, -x pb-sequel option is for CLR data, not for HiFi data. You should use `-x pb-hifi` if your data is HiFi.

Yoshinori

**Comment by kiranpatil222** [comment]
Hi @yfukasawa , Thank you for the clarification, Now worked perfectly got results,

I have converted my local docker image to singularity image as follows

`singularity build longqc.sif docker-daemon://longqc:latest`

I was jus wondering how to use/run the tool using Singularity file command as in docker image
`singularity exec --bind /data  longqc.sif ` /opt or /bin ??

**Comment by yfukasawa** [comment]
Hi @kiranpatil222,

glad to know that it worked fine. unfortunately, I'm not an expert of singularity - never tested LongQC on it.
Some web tutorial says it mounts your home dir automatically like [this page](https://singularity-tutorial.github.io/05-bind-mounts/).

If you face LongQC specific issue in this context, reopen this issue please.

Yoshinori
