### ISSUE TITLE
runqc module errors

### ISSUE THREAD

**Issue by shaniAmare** [yfukasawa/LongQC#6]
Hi @yfukasawa ,

Thanks for this tool kit. It is definitely very flexible and important. I am wondering whether you have fully implemented the `runqc` module within LongQC, or is it still ongoing? I can't seem to find a proper tutorial/readme on this process as well as am facing some issues when running it in python 3.7 (accessing the scripts manually through a cloned repo). If the implementation of `runqc` is complete, I am happy to show the errors so, hopefully, they can be troubleshot.

Thanks heaps,
Shani.

**Comment by yfukasawa** [comment]
Hello @shaniAmare,

thank you for asking `runqc`. This was experimentally developed quite long time ago. I did test at that time, but I need to check for recent datasets, especially for ONT.
Also, sorry for lack of proper documentation. Please I'll prepare it soon.

In the meantime, which platform did you use for your datasets, PacBio Sequel or ONT sequencers?

Yoshi

**Comment by shaniAmare** [comment]
Thanks for your reply @yfukasawa  - I am using this on a PacBio-sequel dataset on a Linux cluster. The size of my file is in the range of ~115 GB. I'm attaching the error below:

```
lq_sequel:2020-06-19 11:26:50,135:240:INFO:Started sequel platform QC for /stornext/transcr_bench_PacBio/long_term/H201SC20030389/00.RawData/S5R
lq_sequel:2020-06-19 11:26:50,136:246:WARNING:sts.xml is missing. Productivity won't be shown
Traceback (most recent call last):
  File "/stornext/long_read_benchmark/LongQC/longQC.py", line 920, in <module>
    main(args)
  File "/stornext/long_read_benchmark/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/stornext/long_read_benchmark/LongQC/longQC.py", line 50, in command_run
    lq_sequel.run_platformqc(args.raw_data_dir, args.out, suffix=suf)
  File "/stornext/long_read_benchmark/LongQC/lq_sequel.py", line 252, in run_platformqc
    [subr_bam_p, scrap_bam_p] = get_bam_path(data_path, logger)
  File "/stornext/long_read_benchmark/LongQC/lq_sequel.py", line 204, in get_bam_path
    logger.ERROR("bam files are missing in %s" % d)
AttributeError: 'Logger' object has no attribute 'ERROR'
```
Wondering why it says the BAM file is missing. I am adding the correct path here.

I will attach the log file as well
[log_sequel_platformqc_m64087_200413_100303.subreads.raw.txt](https://github.com/yfukasawa/LongQC/files/4801975/log_sequel_platformqc_m64087_200413_100303.subreads.raw.txt)

Thanks!
Shani.

**Comment by yfukasawa** [comment]
Thank you for sharing information, @shaniAmare!
sampleqc can be run just with a usual sequence file.

however, runqc requires some additional key files from a sequencer, and input assumes its raw file structure (page 123 of [this file](https://www.pacb.com/wp-content/uploads/SMRT_Link_User_Guide_v700.pdf) explains structure).
In Sequel cases, minimum requirements are `xxx.subreads.bam` and `xxx.scraps.bam`.
`scrapas.bam` could be missing in your path, and as long as I know this file is not always available (some companies/institutes don't provide this).

I hope this helps.

Best,
Yoshi

**Comment by chaikhi-soumaya** [comment]
Hello, 
please I have an error while running the command longqc, the error is as follow
ValueError: truncated quality string in [my file fastq path]
can someone help, please.
