### ISSUE TITLE
Docker run error

### ISSUE THREAD

**Issue by crazysummerW** [yfukasawa/LongQC#61]
hi,
I download the Dockerfile and then build the image against it.
When I run it, I get the following error:
```
docker run -it longqc:latest /bin/bash
usage: LongQC [-h] [-v] {runqc,sampleqc,help} ...
LongQC: error: argument {runqc,sampleqc,help}: invalid choice: '/bin/bash' (choose from 'runqc', 'sampleqc', 'help')
```

Can't I enter the container for interactive operations?

Looking forward to your reply. 
Thanks.

**Comment by yfukasawa** [comment]
Hi, sorry for late reply.

It would be possible to do interactive operation(s).
I'm sorry to say, but this question is out of support for LongQC. please ask details of docker usage at the docker community.

Thanks!
