### ISSUE TITLE
Error 1 for make file

### ISSUE THREAD

**Issue by Hedi65** [yfukasawa/LongQC#62]
Dear developer

i followed all the steps suggested by you in order to install longQC. however, I'm getting error while compiling the package.

~/Downloads$ cd LongQC/minimap2-coverage && make
cc -c -g -O2 -Wall -Wc++-compat -DHAVE_KALLOC  minimap2-coverage.c -o minimap2-coverage.o
minimap2-coverage.c:4:10: fatal error: zlib.h: No such file or directory
    4 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:29: minimap2-coverage.o] Error 1

any help is appreciated.

**Comment by yfukasawa** [comment]
Hi @Hedi65 ,

Thanks for having your interests in our tool.
Which OS did you try to install LongQC to?
The cause looks the lack of the header file (or library) called `zlib.h`.
You would be able to find how to install zlib easily as it's a famous lib.

I hope this helps.

Y.

**Comment by Hedi65** [comment]
thanks, i am using Linux and I installed zlib.h. the problem is solved.

**Comment by yfukasawa** [comment]
all right, I'm glad to know that it was resolved.
