### ISSUE TITLE
More explanations on `sampleqc` module

### ISSUE THREAD

**Issue by shaniAmare** [yfukasawa/LongQC#7]
Hi @yfukasawa ,

Again, thanks heaps for this wonderful tool. 

Could you kindly explain a bit of what happens in/logic behind (or point me to a location where I can find a thorough explanation) the `sampleqc` step? It seems to be generating multiple fastq files at the moment (I started processing only ~1 hour ago). I executed the following script:
`python longQC.py sampleqc -x pb-sequel -p 8 -o ${OUT_DIR}/${subdir} ${BAM}`

Cheers,
Shani.

**Comment by yfukasawa** [comment]
Let me merge this to #8.

**Comment by shaniAmare** [comment]
Yes, it makes sense! thanks!
