### ISSUE TITLE
Error in running LongQC `sampleqc`

### ISSUE THREAD

**Issue by shaniAmare** [yfukasawa/LongQC#8]
Hello @yfukasawa ,

I am running `LongQC `on my PacBio data with the following script.
`python longQC.py sampleqc -x pb-sequel -d -p 8 -m 2 -o ${OUT_DIR}/RAW/${subdir} ${BAM}`

It seems like something is happening (it generates a fastq file in the analysis directory), but in the end, I get the following error:
```
longQC:2020-06-19 01:31:56,627:348:INFO:Summary table /stornext/General/data/
/long_read_benchmark/LongQC_output/RAW/S1R/longqc_sdust.txt was made.
Traceback (most recent call last):
  File "/stornext/General/data/long_read_benchmark/LongQC/longQC.py", line 920, in <module>
    main(args)
  File "/stornext/General/data/long_read_benchmark/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/stornext/General/data/long_read_benchmark/LongQC/longQC.py", line 351, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
  File "/home/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```
Also, the `figs ` and the `analysis/minimap2` folders are empty.

I have loaded minimap2 into my PATH:
`echo $PATH: /stornext/System/data/apps/minimap2/minimap2-2.17/bin:/stornext/System/data/apps/python/python-3.7.0/bin:/stornext/System/data/apps/anaconda2/anaconda2-2019.10/condabin:/stornext/System/data/apps/R/R-3.6.1/lib64/R/bin:/stornext/System/data/apps/hdf5/hdf5-1.8.20/bin:/stornext/System/data/apps/java/java-1.8.0_131/bin:/stornext/System/data/apps/scala/scala-2.12.2/bin:/usr/local/bioinf/bin:/stornext/System/data/apps/fastqc/fastqc-0.11.8/bin:/stornext/System/data/apps/samtools/samtools-1.7/bin:/usr/local/bioinf/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/users/allstaff/bin/Linux:/home/users/all_users/bin:/home/users/user/.local/bin`

What is happening? Can you please explain whether I'm doing something wrong here. It would be great to use your tool for our analysis!

Thanks and I hope to hear from you soon!
Shani.

**Comment by yfukasawa** [comment]
Hello @shaniAmare,

Thank you for your interest!
and, I'm sorry to hear some error happened. Let me dig into the cause.

Your usage has no issue, and the problem happened in longqc_sdust.txt making stage.

Is the file size of `/stornext/General/data/
/long_read_benchmark/LongQC_output/RAW/S1R/longqc_sdust.txt` bigger than 0?
When run goes well, this file should have some stats for each read. Also, the number of lines in this file should be the same with the number of reads.
Some plots such as read length dist are generated from this file, hence issue for this file caused no figure file.

May I ask also input file size (e.g. gigabytes) and environment? Did you run LongQC on a cluster, or a local machine?

Best,
Yoshi

**Comment by yfukasawa** [comment]
And, please no worry for the path of minimap2.
This tool uses a bit modified minimap2, and it is located under LongQC/minimap2_mod.

If compile was successful, you can see below message. sdust is the program to make longqc_sdust.txt

>user@d1c5289b04d8:~$ ./LongQC/minimap2_mod/sdust
>Usage: sdust [-w 64] [-t 20] <in.fa>

**Comment by shaniAmare** [comment]
Hi @yfukasawa ,

Thanks for your reply Yoshi. The size of the `/stornext/General/data/ /long_read_benchmark/LongQC_output/RAW/S1R/longqc_sdust.txt` is actually zero. So were the `tmp` files generated while the process is run.

I use LongQC on the cluster, and the size of the BAM files I input are in the range of ~1GB (ccs file) OR ~115 GB (subreads). LongQC identifies as my BAM file as compressed, but those BAM files are not compressed.

I'm attaching a full log file below (for a ccs file), and as you may see I don't get the message `/LongQC/minimap2_mod/sdust
Usage: sdust [-w 64] [-t 20] <in.fa>`, and also the `minimap2` directory is empty.

[log_longQC_sampleqc.txt](https://github.com/yfukasawa/LongQC/files/4801890/log_longQC_sampleqc.txt)

Thanks again,
Shani.

**Comment by yfukasawa** [comment]
Hi @shaniAmare,

Thank you for your feedback! subread file might require a relatively high memory node.
The location of longQC.py is `/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LongQC/`?

I feel compilation of modified minimap2 had some issues.
Could you please try below? (this [step](https://github.com/yfukasawa/LongQC#2-minimap2))
`cd /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LongQC/minimap2_mod && make extra`
Then, if compilation works fine, you would see some message through `/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LongQC/minimap2_mod/sdust`.

I hope this will resolve issue.

Best,
Yoshi

**Comment by shaniAmare** [comment]
Hi @yfukasawa ,

Thanks for the clarification. I did what you said and these are what I get in the figs - some plots you have in the readme of this repo are not there. Also the second plot looks empty? Wonder why that is... please help! many thanks! Shani.

![fig_longQC_sampleqc_masked_region](https://user-images.githubusercontent.com/43805905/85484245-c8ea9880-b609-11ea-8b9c-b4c48e87b554.png)
![fig_longQC_sampleqc_average_qv](https://user-images.githubusercontent.com/43805905/85484246-ca1bc580-b609-11ea-991f-02bb8620b0c5.png)
![fig_longQC_sampleqc_gcfrac](https://user-images.githubusercontent.com/43805905/85484248-cab45c00-b609-11ea-8713-1ab7d6f9c483.png)
![fig_longQC_sampleqc_length](https://user-images.githubusercontent.com/43805905/85484250-cab45c00-b609-11ea-9648-c21f6a0326be.png)

**Comment by shaniAmare** [comment]
Hi @yfukasawa ,

So what I realised is, I get a full web report when I run sampleqc on CCS BAM files and not one Raw subread bam files. Is there a reason for this?

Also, can you kindly explain what each plot means as well?

Many thanks!
Shani.

**Comment by shaniAmare** [comment]
Also can you please explain what this plot means for my PacBio Sequel II data?

![image](https://user-images.githubusercontent.com/43805905/85807533-8bb31180-b795-11ea-971e-480271ab7ad0.png)

**Comment by yfukasawa** [comment]
Hi @shaniAmare,

Thank you for giving me the feedback!
I have been snowed under, let me visit point by point below.

>Also the second plot looks empty? Wonder why that is...

![](https://user-images.githubusercontent.com/43805905/85484246-ca1bc580-b609-11ea-991f-02bb8620b0c5.png)

I think you applied a Sequel subread file, and if this is the case, this is an expected plot. Please no worry.
Sequel subreads.bam has quality values for each base (equiv to the fourth line of fastq), but indeed they are just place holders. All of bases have the same value (in usual, it is '!'). Hence it looks empty.
For ONT or PB RS-II datastes, this plot should show how QV varies along with length. For example, short reads show dropped QV in some non-ideal libraries.

![](https://user-images.githubusercontent.com/43805905/85484245-c8ea9880-b609-11ea-8b9c-b4c48e87b554.png)
This plot simply shows fraction of masked bases for each read. From my experiences, a peak shows around < 0.2. In some very rare cases like sequencers had some issues, a lot of weird reads having very low complexity can be generated. They can appear as another peak at high value, say >0.7. As there is no such a peak, your data should not have such weird reads.


![](https://user-images.githubusercontent.com/43805905/85484248-cab45c00-b609-11ea-8713-1ab7d6f9c483.png)

![](https://user-images.githubusercontent.com/43805905/85484250-cab45c00-b609-11ea-9648-c21f6a0326be.png)

These plots are GC fraction and read length plots for each read. Blue one in the GC plot shows 
Length plots basically depends on the size selection step in PacBio. 
Blue line in GC plot shows GC fraction for whole length (no chunking) of each read, and orange one is chunked by 150bp. Blue one normally has a single shaper peak, and more sensitive for contaminations.
Let me put an example below.

![F2 large](https://user-images.githubusercontent.com/6773999/85852708-d0e93a80-b7b9-11ea-8e84-246cf80308bb.jpg)

This datasets has some bacterial contamination in plant WGS, and plots A-C came from the original dataset. You may see some spikes surrounded by orange boxes. After manual removal of bacterial reads, some spikes disappeared in D-F.

![](https://user-images.githubusercontent.com/43805905/85807533-8bb31180-b795-11ea-971e-480271ab7ad0.png)

This plot shows coverage change in your dataset along with length. reads whose length range 1-3000bp and 3001-6000bp have roughly around 100x coverage in your dataset. but longer reads 
 binned in 6001-9000bp have a double coverage. mmm, ideally some homogeneous coverage is expected regardless of read length change. the above GC plot came from the same dataset?

Y.

**Comment by yfukasawa** [comment]
Hi @shaniAmare,

>So what I realised is, I get a full web report when I run sampleqc on CCS BAM files and not one Raw subread bam files. Is there a reason for this?

Sorry for inconvenience. For raw bam file processing, RAM error might have happened due to bigger size. May I ask a log for minimap2 and RAM size of the machine?
log exists in {OUPUT}/analysis/minimap2/coverage_err.txt

[M::worker_pipeline::317.782*13.53] mapped 5000 sequences. (**Peak RSS: 70.236 GB**)

The above line is an example, and peak RSS shows memory usage. It might be bigger than machine RAM. Throughput increment for long read sequencer is faster than I expected, so I have been changing memory management in the modified minimap2.

If this is the case, [a new branch version](https://github.com/yfukasawa/LongQC/tree/minimap2_update) might be helpful, but tentatively, please let me ask.

Thank you your feedback!

Best,
Y.
